# Generated by Django 5.1.4 on 2024-12-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_recipe_image_recipestep_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="recipes"),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="recipes"),
        ),
    ]
