# Generated by Django 5.1.4 on 2025-01-13 11:32

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_image_recipe_image_1_remove_recipestep_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipestep",
            options={"ordering": ["step_number"]},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_1",
            field=models.ImageField(
                blank=True, default="", upload_to=main.models.get_recipe_image_path
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_2",
            field=models.ImageField(
                blank=True, default="", upload_to=main.models.get_recipe_image_path
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_3",
            field=models.ImageField(
                blank=True, default="", upload_to=main.models.get_recipe_image_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipestep",
            unique_together={("recipe", "step_number")},
        ),
    ]
